name: 'plant_pulse'
version: '1.0.0'
config-version: 2

profile: 'dbt_plant'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  plant_pulse:
    staging:
      +materialized: view
    marts:
      +materialized: table
